services:
  iknds:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_ID=$USER_ID
        - GROUP_ID=$GROUP_ID
    ports:
      - "3000:3000"
    volumes:
      - ../:/workspace
    tty: true
    command: tail -f /dev/null
